name: Deploy to surge.sh

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1
            -   name: Setup node
                uses: actions/setup-node@v1
                with:
                    node-version: 16
            -   name: Install surge
                run: npm install -g surge
            -   name: Install revealjs
                run: npm install
            -   name: Extract branch name
                shell: bash
                run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
                id: extract_branch
            -   uses: dswistowski/surge-sh-action@v1
            -   name: Deploy to {{ steps.extract_branch.outputs.branch }}.surge.sh
                with:
                    domain: { { steps.extract_branch.outputs.branch } }.surge.sh
                    project: $GITHUB_WORKSPACE
                    login: ${{ secrets.SURGE_LOGIN }}
                    token: ${{ secrets.SURGE_TOKEN }}
