name: Deploy to surge.sh

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            -   uses: actions/checkout@v1
            -   name: Setup node
                uses: actions/setup-node@v1
                with:
                    node-version: 16
            -   name: Install surge
                run: npm install -g surge
            -   name: Install revealjs
                run: npm install
            -   name: Extract branch name
                shell: bash
                run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
                id: extract_branch
            -   name: Deploy https://val-${{ steps.extract_branch.outputs.branch }}.surge.sh to surge.sh
                env:
                    SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
                    SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
                run: surge --project $GITHUB_WORKSPACE --domain https://val-${{ steps.extract_branch.outputs.branch }}.surge.sh
