name: Deploy to surge.sh

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm install -g surge
      - run: surge ./ nxs-${{ github.base_ref }} --token ${{ secrets.SURGE_TOKEN }}
